# Build stage
FROM node:20-bullseye AS builder

# Install dependencies needed for Zola
RUN apt-get update && apt-get install -y wget unzip \
    && wget https://github.com/getzola/zola/releases/download/v0.19.2/zola-v0.19.2-x86_64-unknown-linux-gnu.tar.gz \
    && tar -xvzf zola-v0.19.2-x86_64-unknown-linux-gnu.tar.gz -C /usr/local/bin \
    && rm zola-v0.19.2-x86_64-unknown-linux-gnu.tar.gz

# Set working directory
WORKDIR /app

# Copy package files and install deps
COPY package*.json ./
RUN npm install

# Copy the whole project (including config.toml)
COPY . .

# Build frontend
RUN npm run build

# Build Zola site (explicit root to avoid config.toml issues)
RUN zola build --root /app

# ---- Production image ----
FROM debian:bullseye-slim

# Install Zola only (to serve the site)
RUN apt-get update && apt-get install -y wget unzip \
    && wget https://github.com/getzola/zola/releases/download/v0.19.2/zola-v0.19.2-x86_64-unknown-linux-gnu.tar.gz \
    && tar -xvzf zola-v0.19.2-x86_64-unknown-linux-gnu.tar.gz -C /usr/local/bin \
    && rm zola-v0.19.2-x86_64-unknown-linux-gnu.tar.gz

WORKDIR /app

# Copy built site
COPY --from=builder /app/public ./public
COPY --from=builder /app/config.toml ./config.toml

# Expose port (Render needs a port)
EXPOSE 8080

# Run Zola server on port 8080
CMD ["zola", "serve", "--root", "/app", "--interface", "0.0.0.0", "--port", "8080"]
